name: jprogress
description: Circle Progress Indecator By Just Codes Developers.
version: 0.0.1
author: Just Codes Developers (Ayman Yassin)
homepage: https://github.com/AymanYassinn/JProgress

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

