name: jprogress
description: Custom Progress Indicators By Just Codes Developers Countdown - Download Progress - Upload Progress.
version: 0.0.3
homepage: https://github.com/AymanYassinn/
repository: https://github.com/AymanYassinn/JProgress

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

